api_autodiscovery: "![BygZEgWAoCHll3megfSw/Q==]"
http:
  port: "![5SJ5zdLWhFKgpr1NkAA8LQ==]"
#hapi_key: "5bb0c26b-d0f6-4ca8-a69a-edcf77a0eb24"
hapi_key: "![je4I/YeqayAloHNtfNf8dP5gCaED6Be7oehr8Dquz+GqchDGyB/7otMFBOmG8Ztf]"