http:
  port: "![5SJ5zdLWhFKgpr1NkAA8LQ==]"
netsuite:
  email: "![fjO/wE95MuFoFp+Cthm/x6PpnTZKmltfVICIMeXpPlvJRKon6EO0nbwImijDo/BQ]"
  password: "![0/1mYMB65kgEXeP+oC2NTg==]"
  account: "![30i8ZLfhZ6Sao+6Eq4hDAw==]"
  roleID: "![ZIMxkmRwTtSfDcX7mtcaXg==]"
  appID: "![QLq6Ob5j0tmXYYYQQftqjrxpqJmrVP6vWUS6Yz8Q3wunhLNYTWHd9c2Ovq1E14zq]"
